#!/usr/bin/env python3

import ray
import time

ray.init()

@ray.remote
def cade_task():
    import tensorflow as tf

def run_benchmark():
    start = time.time()
    futures = [cade_task.remote() for _ in range(32)]
    ray.get(futures)
    end = time.time()
    dur_s = end - start
    return dur_s

durations = []
for _ in range(3):
    durations.append(run_benchmark())

print('Durations:')
for dur_s in durations:
    print(f'{dur_s:.02f}')
